# Cleaning Data

In [ ]:
Unduh data CSV dari: https://github.com/saadidrees/dataset_covid_19_symptoms/blob/master/dataset_symps_covid19.csv

Import library yang dibutuhkan

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("dataset_1.csv")

In [5]:
print(df.dtypes)

age                        float64
sex                         object
country_new                 object
chronic_disease             object
date_onset_symptoms         object
date_confirmation           object
date_death_or_discharge     object
outcome                     object
Fever                      float64
Cough                      float64
Fatigue                    float64
Sore throat                float64
Runny nose                 float64
Shortness of breath          int64
Vomiting                   float64
full_symptoms               object
dtype: object

In [6]:
df.describe()

,age,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
count,1424.000000,1897.000000,1897.000000,1897.000000,1897.000000,1897.000000,1897.000000,1897.000000
mean,50.516503,0.569953,0.316342,0.117080,0.064365,0.044386,0.042172,0.016078
std,18.645291,1.328923,0.823627,0.403183,0.276879,0.222546,0.216203,0.127371
min,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,36.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,52.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,65.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,96.000000,54.200000,30.100000,11.100000,6.100000,4.200000,4.000000,1.500000

In [7]:
df.head()

,age,sex,country_new,chronic_disease,date_onset_symptoms,date_confirmation,date_death_or_discharge,outcome,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting,full_symptoms
0,60.0,male,Japan,NaN,03.02.2020,18.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0,0.0,"fever, severe pneumonia"
1,45.0,male,Japan,NaN,08.02.2020,10.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0,0.0,fever
2,25.0,male,Japan,NaN,07.02.2020,08.02.2020,NaN,NaN,1.0,1.0,0.0,1.0,0.0,0,0.0,"cough, fever, sore throat"
3,45.0,male,Japan,NaN,02.02.2020,15.02.2020,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0,0.0,"cough, fever"
4,85.0,male,Japan,NaN,09.02.2020,18.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,1,0.0,"dyspnea, fever"

Hapus kolom yang tidak dibutuhkan

In [8]:
hapus_kolom = ['country_new','chronic_disease','date_onset_symptoms','full_symptoms']

In [9]:
df.drop(hapus_kolom, inplace = True, axis = 1)

In [10]:
df.head()

,age,sex,date_confirmation,date_death_or_discharge,outcome,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
0,60.0,male,18.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0,0.0
1,45.0,male,10.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0,0.0
2,25.0,male,08.02.2020,NaN,NaN,1.0,1.0,0.0,1.0,0.0,0,0.0
3,45.0,male,15.02.2020,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0,0.0
4,85.0,male,18.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,1,0.0

In [11]:
print(df.dtypes)

age                        float64
sex                         object
date_confirmation           object
date_death_or_discharge     object
outcome                     object
Fever                      float64
Cough                      float64
Fatigue                    float64
Sore throat                float64
Runny nose                 float64
Shortness of breath          int64
Vomiting                   float64
dtype: object

In [12]:
df["Shortness of breath"] = df["Shortness of breath"].astype("float64")

In [13]:
print(df.dtypes)

age                        float64
sex                         object
date_confirmation           object
date_death_or_discharge     object
outcome                     object
Fever                      float64
Cough                      float64
Fatigue                    float64
Sore throat                float64
Runny nose                 float64
Shortness of breath        float64
Vomiting                   float64
dtype: object

In [16]:
df.isnull().sum()

age                         473
sex                         456
date_confirmation            38
date_death_or_discharge    1707
outcome                    1426
Fever                         0
Cough                         0
Fatigue                       0
Sore throat                   0
Runny nose                    0
Shortness of breath           0
Vomiting                      0
dtype: int64

In [17]:
df.shape

(1897, 12)

Hapus semua baris yang mengandung NaN

In [19]:
df.dropna(axis=0)

,age,sex,date_confirmation,date_death_or_discharge,outcome,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
132,44.0,female,21.01.2020,29.01.2020,discharged,1.0,0.0,1.0,0.0,0.0,0.0,0.0
136,39.0,female,24.01.2020,03.02.2020,discharged,1.0,0.0,1.0,0.0,1.0,0.0,0.0
170,30.0,male,15.01.2020,15.01.2020,discharged,1.0,1.0,0.0,1.0,0.0,0.0,0.0
183,32.0,male,24.01.2020,17.01.2020,discharged,1.0,1.0,0.0,0.0,0.0,1.0,0.0
184,66.0,male,23.01.2020,19.02.2020,discharged,1.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1769,66.0,male,23.01.2020,19.02.2020,discharged,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1772,55.0,male,24.01.2020,05.02.2020,discharge,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1776,40.0,male,25.01.2020,08.02.2020,discharged,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1798,1.0,female,08.02.2020,17.02.2020,discharged,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1827,52.0,female,11.03.2020,11.03.2020,death,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Hapus baris yang mengandung death, died, deceased (kolom outcome)

In [43]:
df['outcome'].head(60)

132     discharged
136     discharged
170     discharged
183     discharged
184     discharged
185     discharged
187     discharged
212     discharged
217     Discharged
218     Discharged
225          death
263           dead
400           died
434          death
438      discharge
477      discharge
535          death
580      discharge
584          death
601      discharge
607      discharge
623      discharge
625      discharge
650      discharge
651      discharge
652      discharge
658      discharge
702      discharge
720           died
726           died
730           died
739           died
844       Deceased
1162     discharge
1163     discharge
1164     discharge
1177         death
1181     discharge
1184         death
1207          dead
1411     discharge
1442          died
1443          died
1444          died
1445     recovered
1446          died
1448     recovered
1449     recovered
1450     recovered
1451     recovered
1452     recovered
1455     recovered
1457     recovered
1458     recovered
1459     recovered
1460          died
1462          died
1463          died
1464          died
1465          died
Name: outcome, dtype: object

In [57]:
df['outcome'].tail(40)

1540          died
1541          died
1542          died
1543          died
1545          died
1546          died
1548          died
1549          died
1554          died
1556          died
1557          died
1558          died
1563          died
1567          died
1569          died
1571          died
1572          died
1573          died
1575          died
1577          died
1578          died
1579          died
1581          died
1582          died
1638    discharged
1658     discharge
1660          died
1675         death
1708     discharge
1709     discharge
1717    discharged
1721     discharge
1722     discharge
1766    discharged
1768    discharged
1769    discharged
1772     discharge
1776    discharged
1798    discharged
1827         death
Name: outcome, dtype: object

In [60]:
df.drop([225, 263, 400, 434], axis = 0, inplace = True)

C:\Users\alfen\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [61]:
df['outcome'].head(60)

132     discharged
136     discharged
170     discharged
183     discharged
184     discharged
185     discharged
187     discharged
212     discharged
217     Discharged
218     Discharged
438      discharge
477      discharge
535          death
580      discharge
584          death
601      discharge
607      discharge
623      discharge
625      discharge
650      discharge
651      discharge
652      discharge
658      discharge
702      discharge
720           died
726           died
730           died
739           died
844       Deceased
1162     discharge
1163     discharge
1164     discharge
1177         death
1181     discharge
1184         death
1207          dead
1411     discharge
1442          died
1443          died
1444          died
1445     recovered
1446          died
1448     recovered
1449     recovered
1450     recovered
1451     recovered
1452     recovered
1455     recovered
1457     recovered
1458     recovered
1459     recovered
1460          died
1462          died
1463          died
1464          died
1465          died
1467          died
1468          died
1470          died
1471          died
Name: outcome, dtype: object

In [63]:
df.drop([535, 584, 720, 726, 730, 739, 844, 1177, 1184, 1207, 1442, 1443, 1444, 1446, 1460, 1462, 1463, 1464, 1465, 1467, 1468, 1470, 1471], axis = 0, inplace = True)

In [64]:
df['outcome'].head(60)

132     discharged
136     discharged
170     discharged
183     discharged
184     discharged
185     discharged
187     discharged
212     discharged
217     Discharged
218     Discharged
438      discharge
477      discharge
580      discharge
601      discharge
607      discharge
623      discharge
625      discharge
650      discharge
651      discharge
652      discharge
658      discharge
702      discharge
1162     discharge
1163     discharge
1164     discharge
1181     discharge
1411     discharge
1445     recovered
1448     recovered
1449     recovered
1450     recovered
1451     recovered
1452     recovered
1455     recovered
1457     recovered
1458     recovered
1459     recovered
1474          died
1475          died
1476          died
1478          died
1479          died
1482          died
1484          died
1485          died
1486          died
1487          died
1488          died
1491          died
1492          died
1493          died
1494          died
1495          died
1502          died
1503          died
1504          died
1506          died
1507          died
1508          died
1509          died
Name: outcome, dtype: object

In [65]:
df.drop([1474, 1475, 1476, 1478, 1479, 1482, 1484, 1485, 1486, 1487, 1488, 1491, 1492, 1493, 1494, 1495, 1502, 1503, 1504, 1506, 1507, 1508, 1509], axis = 0, inplace = True)

In [66]:
df['outcome'].head(60)

132     discharged
136     discharged
170     discharged
183     discharged
184     discharged
185     discharged
187     discharged
212     discharged
217     Discharged
218     Discharged
438      discharge
477      discharge
580      discharge
601      discharge
607      discharge
623      discharge
625      discharge
650      discharge
651      discharge
652      discharge
658      discharge
702      discharge
1162     discharge
1163     discharge
1164     discharge
1181     discharge
1411     discharge
1445     recovered
1448     recovered
1449     recovered
1450     recovered
1451     recovered
1452     recovered
1455     recovered
1457     recovered
1458     recovered
1459     recovered
1510          died
1511          died
1512          died
1513          died
1514          died
1515          died
1516          died
1517          died
1518          died
1519          died
1520          died
1521          died
1523          died
1524          died
1525          died
1528          died
1530          died
1534          died
1535          died
1537          died
1538          died
1540          died
1541          died
Name: outcome, dtype: object

In [67]:
df.drop([1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1523, 1524, 1525, 1528, 1530, 1534, 1535, 1537, 1538, 1540, 1541], axis = 0, inplace = True)

In [71]:
df['outcome'].head(60)

132     discharged
136     discharged
170     discharged
183     discharged
184     discharged
185     discharged
187     discharged
212     discharged
217     Discharged
218     Discharged
438      discharge
477      discharge
580      discharge
601      discharge
607      discharge
623      discharge
625      discharge
650      discharge
651      discharge
652      discharge
658      discharge
702      discharge
1162     discharge
1163     discharge
1164     discharge
1181     discharge
1411     discharge
1445     recovered
1448     recovered
1449     recovered
1450     recovered
1451     recovered
1452     recovered
1455     recovered
1457     recovered
1458     recovered
1459     recovered
1542          died
1543          died
1545          died
1546          died
1548          died
1549          died
1554          died
1556          died
1557          died
1558          died
1563          died
1567          died
1569          died
1571          died
1572          died
1573          died
1575          died
1577          died
1578          died
1579          died
1581          died
1582          died
1638    discharged
Name: outcome, dtype: object

In [72]:
df.drop([1542, 1543, 1545, 1546, 1548, 1549, 1554, 1556, 1557, 1558, 1563, 1567, 1569, 1571, 1572, 1573, 1575, 1577, 1578, 1579, 1581, 1582], axis = 0, inplace = True)

In [73]:
df['outcome'].head(60)

132     discharged
136     discharged
170     discharged
183     discharged
184     discharged
185     discharged
187     discharged
212     discharged
217     Discharged
218     Discharged
438      discharge
477      discharge
580      discharge
601      discharge
607      discharge
623      discharge
625      discharge
650      discharge
651      discharge
652      discharge
658      discharge
702      discharge
1162     discharge
1163     discharge
1164     discharge
1181     discharge
1411     discharge
1445     recovered
1448     recovered
1449     recovered
1450     recovered
1451     recovered
1452     recovered
1455     recovered
1457     recovered
1458     recovered
1459     recovered
1638    discharged
1658     discharge
1660          died
1675         death
1708     discharge
1709     discharge
1717    discharged
1721     discharge
1722     discharge
1766    discharged
1768    discharged
1769    discharged
1772     discharge
1776    discharged
1798    discharged
1827         death
Name: outcome, dtype: object

In [74]:
df.drop([1660, 1675, 1827], axis = 0, inplace = True)

In [80]:
df.head(50)

,age,sex,date_confirmation,date_death_or_discharge,outcome,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
132,44.00,female,21.01.2020,29.01.2020,discharged,1.0,0.0,1.0,0.0,0.0,0.0,0.0
136,39.00,female,24.01.2020,03.02.2020,discharged,1.0,0.0,1.0,0.0,1.0,0.0,0.0
170,30.00,male,15.01.2020,15.01.2020,discharged,1.0,1.0,0.0,1.0,0.0,0.0,0.0
183,32.00,male,24.01.2020,17.01.2020,discharged,1.0,1.0,0.0,0.0,0.0,1.0,0.0
184,66.00,male,23.01.2020,19.02.2020,discharged,1.0,1.0,0.0,0.0,0.0,0.0,0.0
185,40.00,male,25.01.2020,08.02.2020,discharged,1.0,1.0,0.0,0.0,0.0,0.0,0.0
187,33.00,male,27.01.2020,27.01.2020,discharged,1.0,0.0,1.0,1.0,0.0,0.0,0.0
212,1.00,female,08.02.2020,17.02.2020,discharged,0.0,0.0,0.0,0.0,0.0,0.0,0.0
217,30.00,female,24.01.2020,12.02.2020,Discharged,1.0,1.0,1.0,0.0,0.0,0.0,0.0
218,31.00,male,24.01.2020,12.02.2020,Discharged,1.0,1.0,0.0,0.0,0.0,0.0,0.0
438,29.00,male,24.01.2020,28.01.2020,discharge,0.0,0.0,0.0,0.0,0.0,0.0,0.0
477,55.00,male,24.01.2020,05.02.2020,discharge,1.0,0.0,0.0,0.0,0.0,0.0,0.0
580,73.00,male,02.02.2020,21.02.2020,discharge,0.0,0.0,0.0,0.0,0.0,0.0,0.0
601,42.00,female,04.02.2020,20.02.2020,discharge,1.0,1.0,0.0,0.0,1.0,0.0,0.0
607,28.00,female,03.02.2020,22.02.2020,discharge,1.0,0.0,0.0,1.0,0.0,0.0,0.0
623,49.00,female,06.02.2020,20.02.2020,discharge,0.0,1.0,0.0,0.0,0.0,0.0,0.0
625,16.00,female,06.02.2020,20.02.2020,discharge,1.0,1.0,0.0,0.0,0.0,0.0,0.0
650,29.00,male,06.02.2020,22.02.2020,discharge,1.0,0.0,0.0,0.0,0.0,0.0,0.0
651,55.00,female,09.02.2020,18.02.2020,discharge,1.0,0.0,0.0,0.0,1.0,0.0,0.0
652,0.25,female,11.02.2020,20.02.2020,discharge,0.0,1.0,0.0,0.0,1.0,0.0,0.0
658,50.00,male,13.02.2020,26.02.2020,discharge,0.0,0.0,1.0,0.0,0.0,0.0,0.0
702,61.00,male,14.02.2020,26.02.2020,discharge,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1162,55.00,female,09.02.2020,18.02.2020,discharge,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1163,0.25,female,11.02.2020,20.02.2020,discharge,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1164,50.00,male,13.02.2020,26.02.2020,discharge,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1181,61.00,male,14.02.2020,26.02.2020,discharge,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1411,29.00,male,24.01.2020,28.01.2020,discharge,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1445,72.00,male,09.03.2020,27.03.2020,recovered,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1448,34.00,male,09.03.2020,15.03.2020,recovered,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1449,46.00,male,09.03.2020,15.03.2020,recovered,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1450,70.00,male,09.03.2020,19.03.2020,recovered,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1451,41.00,male,09.03.2020,24.03.2020,recovered,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1452,46.00,female,09.03.2020,26.03.2020,recovered,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1455,51.00,female,09.03.2020,18.03.2020,recovered,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1457,30.00,female,09.03.2020,24.03.2020,recovered,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1458,31.00,male,09.03.2020,17.03.2020,recovered,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1459,34.00,male,10.03.2020,17.03.2020,recovered,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1638,39.00,female,24.01.2020,03.02.2020,discharged,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1658,73.00,male,02.02.2020,21.02.2020,discharge,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1708,42.00,female,04.02.2020,20.02.2020,discharge,1.0,1.0,0.0,0.0,1.0,0.0,0.0
1709,28.00,female,03.02.2020,22.02.2020,discharge,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1717,44.00,female,21.01.2020,29.01.2020,discharged,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1721,49.00,female,06.02.2020,20.02.2020,discharge,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1722,16.00,female,06.02.2020,20.02.2020,discharge,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1766,30.00,male,15.01.2020,15.01.2020,discharged,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1768,32.00,male,24.01.2020,17.01.2020,discharged,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1769,66.00,male,23.01.2020,19.02.2020,discharged,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1772,55.00,male,24.01.2020,05.02.2020,discharge,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1776,40.00,male,25.01.2020,08.02.2020,discharged,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1798,1.00,female,08.02.2020,17.02.2020,discharged,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [79]:
df.shape

(50, 12)

Hapus kolom outcome, karena sudah dibersihkan dan tersisa tanggal pasien sembuh

In [81]:
df.drop('outcome', inplace = True, axis = 1)

C:\Users\alfen\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [82]:
df.head(50)

,age,sex,date_confirmation,date_death_or_discharge,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
132,44.00,female,21.01.2020,29.01.2020,1.0,0.0,1.0,0.0,0.0,0.0,0.0
136,39.00,female,24.01.2020,03.02.2020,1.0,0.0,1.0,0.0,1.0,0.0,0.0
170,30.00,male,15.01.2020,15.01.2020,1.0,1.0,0.0,1.0,0.0,0.0,0.0
183,32.00,male,24.01.2020,17.01.2020,1.0,1.0,0.0,0.0,0.0,1.0,0.0
184,66.00,male,23.01.2020,19.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
185,40.00,male,25.01.2020,08.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
187,33.00,male,27.01.2020,27.01.2020,1.0,0.0,1.0,1.0,0.0,0.0,0.0
212,1.00,female,08.02.2020,17.02.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
217,30.00,female,24.01.2020,12.02.2020,1.0,1.0,1.0,0.0,0.0,0.0,0.0
218,31.00,male,24.01.2020,12.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
438,29.00,male,24.01.2020,28.01.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
477,55.00,male,24.01.2020,05.02.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
580,73.00,male,02.02.2020,21.02.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
601,42.00,female,04.02.2020,20.02.2020,1.0,1.0,0.0,0.0,1.0,0.0,0.0
607,28.00,female,03.02.2020,22.02.2020,1.0,0.0,0.0,1.0,0.0,0.0,0.0
623,49.00,female,06.02.2020,20.02.2020,0.0,1.0,0.0,0.0,0.0,0.0,0.0
625,16.00,female,06.02.2020,20.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
650,29.00,male,06.02.2020,22.02.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
651,55.00,female,09.02.2020,18.02.2020,1.0,0.0,0.0,0.0,1.0,0.0,0.0
652,0.25,female,11.02.2020,20.02.2020,0.0,1.0,0.0,0.0,1.0,0.0,0.0
658,50.00,male,13.02.2020,26.02.2020,0.0,0.0,1.0,0.0,0.0,0.0,0.0
702,61.00,male,14.02.2020,26.02.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1162,55.00,female,09.02.2020,18.02.2020,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1163,0.25,female,11.02.2020,20.02.2020,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1164,50.00,male,13.02.2020,26.02.2020,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1181,61.00,male,14.02.2020,26.02.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1411,29.00,male,24.01.2020,28.01.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1445,72.00,male,09.03.2020,27.03.2020,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1448,34.00,male,09.03.2020,15.03.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1449,46.00,male,09.03.2020,15.03.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1450,70.00,male,09.03.2020,19.03.2020,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1451,41.00,male,09.03.2020,24.03.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1452,46.00,female,09.03.2020,26.03.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1455,51.00,female,09.03.2020,18.03.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1457,30.00,female,09.03.2020,24.03.2020,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1458,31.00,male,09.03.2020,17.03.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1459,34.00,male,10.03.2020,17.03.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1638,39.00,female,24.01.2020,03.02.2020,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1658,73.00,male,02.02.2020,21.02.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1708,42.00,female,04.02.2020,20.02.2020,1.0,1.0,0.0,0.0,1.0,0.0,0.0
1709,28.00,female,03.02.2020,22.02.2020,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1717,44.00,female,21.01.2020,29.01.2020,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1721,49.00,female,06.02.2020,20.02.2020,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1722,16.00,female,06.02.2020,20.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1766,30.00,male,15.01.2020,15.01.2020,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1768,32.00,male,24.01.2020,17.01.2020,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1769,66.00,male,23.01.2020,19.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1772,55.00,male,24.01.2020,05.02.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1776,40.00,male,25.01.2020,08.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1798,1.00,female,08.02.2020,17.02.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Rename nama kolom date_death_or_discharge menjadi date_recovered, karena sudah dibersihkan dan tersisa tanggal pasien sembuh

In [85]:
df.rename(
    columns={'date_death_or_discharge' : 'date_recovered'}, 
    inplace = True,
)

C:\Users\alfen\anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [86]:
print(df)

        age     sex date_confirmation date_recovered  Fever  Cough  Fatigue  \
132   44.00  female        21.01.2020     29.01.2020    1.0    0.0      1.0
136   39.00  female        24.01.2020     03.02.2020    1.0    0.0      1.0
170   30.00    male        15.01.2020     15.01.2020    1.0    1.0      0.0
183   32.00    male        24.01.2020     17.01.2020    1.0    1.0      0.0
184   66.00    male        23.01.2020     19.02.2020    1.0    1.0      0.0
185   40.00    male        25.01.2020     08.02.2020    1.0    1.0      0.0
187   33.00    male        27.01.2020     27.01.2020    1.0    0.0      1.0
212    1.00  female        08.02.2020     17.02.2020    0.0    0.0      0.0
217   30.00  female        24.01.2020     12.02.2020    1.0    1.0      1.0
218   31.00    male        24.01.2020     12.02.2020    1.0    1.0      0.0
438   29.00    male        24.01.2020     28.01.2020    0.0    0.0      0.0
477   55.00    male        24.01.2020     05.02.2020    1.0    0.0      0.0
580   73.00    male        02.02.2020     21.02.2020    0.0    0.0      0.0
601   42.00  female        04.02.2020     20.02.2020    1.0    1.0      0.0
607   28.00  female        03.02.2020     22.02.2020    1.0    0.0      0.0
623   49.00  female        06.02.2020     20.02.2020    0.0    1.0      0.0
625   16.00  female        06.02.2020     20.02.2020    1.0    1.0      0.0
650   29.00    male        06.02.2020     22.02.2020    1.0    0.0      0.0
651   55.00  female        09.02.2020     18.02.2020    1.0    0.0      0.0
652    0.25  female        11.02.2020     20.02.2020    0.0    1.0      0.0
658   50.00    male        13.02.2020     26.02.2020    0.0    0.0      1.0
702   61.00    male        14.02.2020     26.02.2020    1.0    0.0      0.0
1162  55.00  female        09.02.2020     18.02.2020    1.0    0.0      0.0
1163   0.25  female        11.02.2020     20.02.2020    0.0    1.0      0.0
1164  50.00    male        13.02.2020     26.02.2020    0.0    0.0      1.0
1181  61.00    male        14.02.2020     26.02.2020    1.0    0.0      0.0
1411  29.00    male        24.01.2020     28.01.2020    0.0    0.0      0.0
1445  72.00    male        09.03.2020     27.03.2020    0.0    1.0      0.0
1448  34.00    male        09.03.2020     15.03.2020    1.0    0.0      0.0
1449  46.00    male        09.03.2020     15.03.2020    1.0    1.0      0.0
1450  70.00    male        09.03.2020     19.03.2020    1.0    1.0      0.0
1451  41.00    male        09.03.2020     24.03.2020    1.0    0.0      0.0
1452  46.00  female        09.03.2020     26.03.2020    0.0    0.0      0.0
1455  51.00  female        09.03.2020     18.03.2020    1.0    1.0      0.0
1457  30.00  female        09.03.2020     24.03.2020    0.0    1.0      0.0
1458  31.00    male        09.03.2020     17.03.2020    0.0    0.0      0.0
1459  34.00    male        10.03.2020     17.03.2020    0.0    0.0      0.0
1638  39.00  female        24.01.2020     03.02.2020    1.0    0.0      1.0
1658  73.00    male        02.02.2020     21.02.2020    0.0    0.0      0.0
1708  42.00  female        04.02.2020     20.02.2020    1.0    1.0      0.0
1709  28.00  female        03.02.2020     22.02.2020    1.0    0.0      0.0
1717  44.00  female        21.01.2020     29.01.2020    1.0    0.0      1.0
1721  49.00  female        06.02.2020     20.02.2020    0.0    1.0      0.0
1722  16.00  female        06.02.2020     20.02.2020    1.0    1.0      0.0
1766  30.00    male        15.01.2020     15.01.2020    1.0    1.0      0.0
1768  32.00    male        24.01.2020     17.01.2020    1.0    1.0      0.0
1769  66.00    male        23.01.2020     19.02.2020    1.0    1.0      0.0
1772  55.00    male        24.01.2020     05.02.2020    1.0    0.0      0.0
1776  40.00    male        25.01.2020     08.02.2020    1.0    1.0      0.0
1798   1.00  female        08.02.2020     17.02.2020    0.0    0.0      0.0

      Sore throat  Runny nose  Shortness of breath  Vomiting
132           0.0         0.0                  0.0       0.0
136           0.0         1.0                  0.0       0.0
170           1.0         0.0                  0.0       0.0
183           0.0         0.0                  1.0       0.0
184           0.0         0.0                  0.0       0.0
185           0.0         0.0                  0.0       0.0
187           1.0         0.0                  0.0       0.0
212           0.0         0.0                  0.0       0.0
217           0.0         0.0                  0.0       0.0
218           0.0         0.0                  0.0       0.0
438           0.0         0.0                  0.0       0.0
477           0.0         0.0                  0.0       0.0
580           0.0         0.0                  0.0       0.0
601           0.0         1.0                  0.0       0.0
607           1.0         0.0                  0.0       0.0
623           0.0         0.0                  0.0       0.0
625           0.0         0.0                  0.0       0.0
650           0.0         0.0                  0.0       0.0
651           0.0         1.0                  0.0       0.0
652           0.0         1.0                  0.0       0.0
658           0.0         0.0                  0.0       0.0
702           0.0         0.0                  0.0       0.0
1162          0.0         1.0                  0.0       0.0
1163          0.0         1.0                  0.0       0.0
1164          0.0         0.0                  0.0       0.0
1181          0.0         0.0                  0.0       0.0
1411          0.0         0.0                  0.0       0.0
1445          0.0         0.0                  0.0       0.0
1448          0.0         0.0                  0.0       0.0
1449          0.0         0.0                  0.0       0.0
1450          1.0         0.0                  0.0       0.0
1451          0.0         0.0                  0.0       0.0
1452          0.0         0.0                  0.0       0.0
1455          0.0         0.0                  0.0       0.0
1457          1.0         0.0                  0.0       0.0
1458          0.0         0.0                  0.0       0.0
1459          0.0         0.0                  0.0       0.0
1638          0.0         1.0                  0.0       0.0
1658          0.0         0.0                  0.0       0.0
1708          0.0         1.0                  0.0       0.0
1709          1.0         0.0                  0.0       0.0
1717          0.0         0.0                  0.0       0.0
1721          0.0         0.0                  0.0       0.0
1722          0.0         0.0                  0.0       0.0
1766          1.0         0.0                  0.0       0.0
1768          0.0         0.0                  1.0       0.0
1769          0.0         0.0                  0.0       0.0
1772          0.0         0.0                  0.0       0.0
1776          0.0         0.0                  0.0       0.0
1798          0.0         0.0                  0.0       0.0

In [87]:
df.head(50)

,age,sex,date_confirmation,date_recovered,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
132,44.00,female,21.01.2020,29.01.2020,1.0,0.0,1.0,0.0,0.0,0.0,0.0
136,39.00,female,24.01.2020,03.02.2020,1.0,0.0,1.0,0.0,1.0,0.0,0.0
170,30.00,male,15.01.2020,15.01.2020,1.0,1.0,0.0,1.0,0.0,0.0,0.0
183,32.00,male,24.01.2020,17.01.2020,1.0,1.0,0.0,0.0,0.0,1.0,0.0
184,66.00,male,23.01.2020,19.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
185,40.00,male,25.01.2020,08.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
187,33.00,male,27.01.2020,27.01.2020,1.0,0.0,1.0,1.0,0.0,0.0,0.0
212,1.00,female,08.02.2020,17.02.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
217,30.00,female,24.01.2020,12.02.2020,1.0,1.0,1.0,0.0,0.0,0.0,0.0
218,31.00,male,24.01.2020,12.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
438,29.00,male,24.01.2020,28.01.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
477,55.00,male,24.01.2020,05.02.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
580,73.00,male,02.02.2020,21.02.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
601,42.00,female,04.02.2020,20.02.2020,1.0,1.0,0.0,0.0,1.0,0.0,0.0
607,28.00,female,03.02.2020,22.02.2020,1.0,0.0,0.0,1.0,0.0,0.0,0.0
623,49.00,female,06.02.2020,20.02.2020,0.0,1.0,0.0,0.0,0.0,0.0,0.0
625,16.00,female,06.02.2020,20.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
650,29.00,male,06.02.2020,22.02.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
651,55.00,female,09.02.2020,18.02.2020,1.0,0.0,0.0,0.0,1.0,0.0,0.0
652,0.25,female,11.02.2020,20.02.2020,0.0,1.0,0.0,0.0,1.0,0.0,0.0
658,50.00,male,13.02.2020,26.02.2020,0.0,0.0,1.0,0.0,0.0,0.0,0.0
702,61.00,male,14.02.2020,26.02.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1162,55.00,female,09.02.2020,18.02.2020,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1163,0.25,female,11.02.2020,20.02.2020,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1164,50.00,male,13.02.2020,26.02.2020,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1181,61.00,male,14.02.2020,26.02.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1411,29.00,male,24.01.2020,28.01.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1445,72.00,male,09.03.2020,27.03.2020,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1448,34.00,male,09.03.2020,15.03.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1449,46.00,male,09.03.2020,15.03.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1450,70.00,male,09.03.2020,19.03.2020,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1451,41.00,male,09.03.2020,24.03.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1452,46.00,female,09.03.2020,26.03.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1455,51.00,female,09.03.2020,18.03.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1457,30.00,female,09.03.2020,24.03.2020,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1458,31.00,male,09.03.2020,17.03.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1459,34.00,male,10.03.2020,17.03.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1638,39.00,female,24.01.2020,03.02.2020,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1658,73.00,male,02.02.2020,21.02.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1708,42.00,female,04.02.2020,20.02.2020,1.0,1.0,0.0,0.0,1.0,0.0,0.0
1709,28.00,female,03.02.2020,22.02.2020,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1717,44.00,female,21.01.2020,29.01.2020,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1721,49.00,female,06.02.2020,20.02.2020,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1722,16.00,female,06.02.2020,20.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1766,30.00,male,15.01.2020,15.01.2020,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1768,32.00,male,24.01.2020,17.01.2020,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1769,66.00,male,23.01.2020,19.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1772,55.00,male,24.01.2020,05.02.2020,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1776,40.00,male,25.01.2020,08.02.2020,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1798,1.00,female,08.02.2020,17.02.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Untuk data cleaning masih kurang:
- Ubah urutan agar sesuai dan lebih rapi
- Tambah kolom jumlah hari untuk pulih
- Ubah gender menjadi 0 dan 1